server:
  port: 6012

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/myprojectmanager?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
